on: 
 push:
   branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: .Net Build
        # You may pin to the exact commit or the version.
        # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
      uses: EasyDesk/action-dotnet-build@v1.0.0
      with:
        # The build configuration to use (defaults to 'Release').
        build-configuration:  Release
        # The path to the project or solution to build (defaults to the current directory).
        path: .

    - name: .NET Core CLI
        # You may pin to the exact commit or the version.
        # uses: baruchiro/github-actions@cfa460ee18f07031ba85ff00d2184fabf03f9f1f
      uses: baruchiro/github-actions@0.0.1
