name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore NuGet packages
      run: nuget.exe restore /Application/SampleWebApplication/packages.config -PackagesDirectory packages -Source https://api.nuget.org/v3/index.json -NonInteractive
      
    - name: restore-nuget-packages
        # You may pin to the exact commit or the version.
        # uses: IT-Service/restore-nuget-packages@ef2531f9b1037fa8ea9b1314f1609a10cc78edad
      uses: IT-Service/restore-nuget-packages@v1
      with:
       # NuGet version
        nuget-version: latest
            # Path to packages.config file
        packages-config-path: packages.config
          # Path to packages directory
        packages-directory-path: packages
       
      
    - name: Restore NuGet packages
      run: dotnet restore ./Application

    - name: Build
      run: dotnet build ./Application

    - name: Test
      run: dotnet test ./Application

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: ./publish
