name: ASP.NET MVC CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.3
    - name: restore-nuget-packages
          # You may pin to the exact commit or the version.
          # uses: IT-Service/restore-nuget-packages@ef2531f9b1037fa8ea9b1314f1609a10cc78edad
      uses: IT-Service/restore-nuget-packages@v1
      with:
       # NuGet version
        nuget-version: latest
 
    
    - name: Restore NuGet packages
      run: nuget restore SampleWebApplication.sln
    - name: Build solution
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /m /nologo /clp:Summary /t:Build ./Application
    - name: Publish application
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /m /nologo /clp:Summary /t:Publish /path/to/SampleWebApplication.csproj
    - name: Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SampleWebApplication
        path: /path/to/SampleWebApplication/bin/Release/PublishOutput
