name: ASP.NET MVC CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Restore NuGet packages
      run: dotnet restore ./Application
    - name: Build solution
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /m /nologo /clp:Summary /t:Build /path/to/SampleWebApplication.sln
    - name: Publish application
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /m /nologo /clp:Summary /t:Publish /path/to/SampleWebApplication.csproj
    - name: Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SampleWebApplication
        path: /path/to/SampleWebApplication/bin/Release/PublishOutput
